name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install libtss-sys1 (Ubuntu x86)
      run: sudo apt-get install libtss-sys1
    - name: Build
      run: cargo +nightly build --verbose --tests
    - name: Run tests
      run: cargo +nightly test --verbose
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-26-intel, macos-latest, windows-latest, windows-11-arm ]
      fail-fast: false
    permissions:
      contents: write
      deployments: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v6
    - name: Install libtss-sys1 (Ubuntu x86)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install libtss-sys1
    - name: Install libtss-sys1 (MacOS x86)
      if: matrix.os == 'macos-26-intel'
      run: brew install tpm2-tss
    - name: Run benchmarks
      run: cargo +nightly bench -- --output-format bencher | tee bench-output.txt
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: Rust Benchmark
        tool: 'cargo'
        output-file-path: bench-output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        summary-always: true
        auto-push: ${{ github.event_name != 'pull_request' }}
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '125%'
        comment-on-alert: true
        fail-on-alert: true